### ISSUE TITLE
Wrong Sketch-Line

### ISSUE THREAD

**Issue by KristjanESPERANTO** [osm-ToniE/ptna#122]
When I'm clicking in the analyses page [1] the tram line 1 of Halle (Saale) I'm getting the Sketch-Line of the tram line 1 from Leipzig [2].

[1] https://ptna.openstreetmap.de/results/DE/SN/DE-SN-MDV-Analysis.html#tram_1
[2] https://overpass-api.de/api/sketch-line?ref=1&network=MDV&style=wuppertal&bg=%23fbba00&fg=%23000000

**Comment by KristjanESPERANTO** [comment]
That would be nice. Thank you for all the work you put into this project.

**Comment by osm-ToniE** [comment]
Easy fix ... will mark all analysis results for all networks as having changes ... some of them invisible (HTML-tags changed only)

**Comment by KristjanESPERANTO** [comment]
That was fast. Thank you!

The same problem appears also when I'm in the Sketch-Line and click another line. But this isn't part of ptna, isn't it?

**Comment by osm-ToniE** [comment]
Right, sketch-line is part of the Overpass API.

All I can provide/pass to the API is 'ref', 'network' and 'operator' (and some 'colour' = back-ground and foreground information)
