### ISSUE TITLE
Add Unroll link for route_master

### ISSUE THREAD

**Issue by nlehuby** [osm-ToniE/ptna#134]
Please consider adding Unroll link for route_master (in addition to osm.org, ID and JOSM)
![image](https://user-images.githubusercontent.com/919962/189418367-a4a7917a-8c28-44a9-ae29-9d71e24acf99.png)

For instance for [this route_master](https://www.openstreetmap.org/relation/9912272) it would be https://jungle-bus.github.io/unroll/route.html?qa=yes&line=9905067

**Comment by osm-ToniE** [comment]
Hi,

- does "unroll" support "&lang=fr" or "=de" or ...

- for 'my' bus 210 here https://jungle-bus.github.io/unroll/route.html?qa=yes&line= 67811 it shows for instance for the first trip only 4 icons (stop) out of 6 stops on the map
  - what needs to be tagged on which OSM object to show this icon (highway=bus_stop on ?, public_transport=platform on node/way/?)

Regards
Toni

**Comment by nlehuby** [comment]
Unroll detect the language from the browser settings. 
The following languages are supported for now : "cs", "de", "en", "es", "fr", "hu", "it", "pl", "pt"
There is a parameter but it's only to get the `name:other_lang` of the stops for the multilingual zones. For instance: https://jungle-bus.github.io/unroll/route.html?name_l10n=ml&line=13374893

For your route map: Unroll uses the role in the relation to get the stops. For a bus route, this is the platform role. And the stops are supposed to be points (so nodes, not ways).
In your case, they are shown actually, but as polygons.
![image](https://user-images.githubusercontent.com/919962/191070020-58c7695e-099a-4e41-b366-f8c97b60ae28.png)
