### ISSUE TITLE
Parcours : accès restreint du chemin ('access'='no') sans 'psv'='yes'. 'bus'='yes', 'bus'=designated

### ISSUE THREAD

**Issue by mgageo** [osm-ToniE/ptna#143]
For the 'busway' tag, the 'designated' value is used as ‘yes’.
Can you add it?

**Comment by osm-ToniE** [comment]
Thanks, do you have a link to the way, so I can check the tags.
Which bus in which analysis report would also help in that case.

**Comment by mgageo** [comment]
way 1287171060
  access = no
  busway = designated
  check_date = 2022-03-23
  highway = service
  maxspeed = 50
  motor_vehicle = private
  oneway = yes
  surface = asphalt
  nd 10067003031
  nd 10067003036

https://ptna.openstreetmap.de/results/FR/BRE/FR-BRE-Star-Analysis.html

https://osm.org/relation/6565007

https://osm.org/way/1287171060

**Comment by osm-ToniE** [comment]
Thanks, I now understand the context: busway*=* implies psv=designated.
I also read [Zone d’arrêt des bus: attributs pour les voies](https://forum.openstreetmap.fr/t/zone-darret-des-bus-attributs-pour-les-voies/27760) and will answer there.

**Comment by osm-ToniE** [comment]
Fix:
1. check for 'psv' settings "m/yes|private|permissive|permit|official|destination|designated/"
2. check for 'psv:conditional' settings any
3. check for 'busway*' settings any
4. check for 'bus', 'trolleybus', 'xxx', ... values i.e. value of 'route' tag = 'xxx'
5. ...

**Comment by osm-ToniE** [comment]
'busway*' = '*' has no effect if 'highway' = 'construction' is set.
