### ISSUE TITLE
Parcours PTv2 : utilise un sens-unique dans le mauvais sens

### ISSUE THREAD

**Issue by mgageo** [osm-ToniE/ptna#146]
The way is the first of on the route and has its ends in common with the second.
https://ptna.openstreetmap.de/results/FR/NOR/FR-NOR-Nomad_Car-Analysis.html#bus_405

https://ptna.openstreetmap.de/relation.php?id=18067013&lang=fr

https://osm.org/way/127048960

![image](https://github.com/user-attachments/assets/e45ef148-79d9-4361-938d-e54c0594692b)

**Comment by osm-ToniE** [comment]
This is a special case where the first way is a one-way which does not have a stop_position of the bus as one of its nodes.

**Comment by osm-ToniE** [comment]
If the second way is not a one-way and both build a loop, it is hard to detect whether the first way (=one-way) is used in the correct or wrong direction and if there is no stop_position. 
Having a stop_position would add some guidance, sometimes.
I have to think about and test some more cases here.
For the time being, the original error case has been solved.
