### ISSUE TITLE
Add relatify links for route=tram

### ISSUE THREAD

**Issue by kudlav** [osm-ToniE/ptna#147]
Hi, Relatify added support for tram routes: https://relatify.monicz.dev/

But the PTNA Web displays Relatify links only for `route=bus`. Can you add these links also for `route=trams`?

![obrazek](https://github.com/user-attachments/assets/cef7172f-9a22-40d7-840b-c8e60d70d61a)

https://ptna.openstreetmap.de/results/CZ/64/CZ-64-IDS_JMK-Analysis.html#A2.2

**Comment by osm-ToniE** [comment]
fixed, see also https://community.openstreetmap.org/t/ptna-news-for-public-transport-network-analysis/8383/192
