### ISSUE TITLE
Add button to manually update an individual analysis

### ISSUE THREAD

**Issue by mcliquid** [osm-ToniE/ptna#151]
There are often some changes in an individual transport network on a particular day / timeframe (timetable change or major construction site). It would be very helpful if there was a button for each transport network analysis that updated this analysis again on an unscheduled basis.
This would enable continuous work on the individual lines and relations and faster action in the event of recurring or newly caused errors.
The button only calculates the analysis in the selected network. To protect the server, you could also introduce a limit, which on the one hand saves resources, but on the other hand does not hinder the work.
Thanks!

Mockup:
<img width="570" alt="image" src="https://github.com/user-attachments/assets/4812568a-3b99-4a4a-b7e7-003de4904041">

**Comment by osm-ToniE** [comment]
This could be a link in the analysis report to '/network.php?analyse=network-name' for instance, where "network-name" is the name of the 'network' being analysed ($PREFIX in the settings.sh file)

**Comment by osm-ToniE** [comment]
This will be a link in the analysis report to '/results/queue.php' without parameters deriving the 'network' to be analysed from the name of the report file
