### ISSUE TITLE
Check for line=bus attached to a bus route

### ISSUE THREAD

**Issue by ENT8R** [osm-ToniE/ptna#78]
According to the OpenStreetMap Wiki, [`line=*`](https://wiki.openstreetmap.org/wiki/Key:line) should only be used for **power lines**. Some mappers still tend to use `line=bus` on bus route relations for reasons I don't know 😄.
Especially as this is no additional information if `route=bus` is also set, this value should not be used at all for bus routes. This is not really an error, but more a warning which should appear if this value is set.
See e.g. https://www.openstreetmap.org/relation/2078316

**Comment by osm-ToniE** [comment]
"The tag 'line' (='%s') is reserved for 'power' = 'line' related tagging. For public transport 'route_master' and 'route' are used."
